---
title: "flat_export_results.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# export_results

```{r development-export_results}
# Prepare the code of your function here
```

# save_as_csv
    
```{r development-save_as_csv}
library(readr)
library(tools)
```
  
```{r function-save_as_csv}
#' Sauvegarde d'un df en csv
#' 
#' @param df df a exporter
#' @param path chemin de sortie
#' @return le chemin de sortie
#' @importFrom tools file_ext #ne pas oublier
#' @importFrom readr write_csv2 #ne pas oublier
#' @export
save_as_csv <- function(df, path){
  
  if (isFALSE(inherits(df,"data.frame"))) {
    stop("Param 'df' must be a dataframe")
  }
  
  if (isFALSE(file_ext(x=path)=="csv")) {
    stop("Param 'path' must have csv extension")
  }
  
  if (isFALSE(dir.exists(dirname(path)))){
    stop("Param 'path' must exist")
  }
    
  write_csv2(df, file = path)
  
  return(path)
    
}
```
  
```{r example-save_as_csv}
mon_dossier_temp <- tempfile(pattern ="savecsv")
dir.create(mon_dossier_temp)
#dans la console : rstudio::filesPanelNaviguate(mon_dossier_temp)
save_as_csv(df=iris, path=file.path(mon_dossier_temp, "output.csv"))
#Ménage :
unlink(mon_dossier_temp, recursive = TRUE)
```
  
```{r tests-save_as_csv}
test_that("save_as_csv works", {
  expect_true(inherits(save_as_csv, "function")) 
  mon_dossier_temp <- tempfile(pattern = "savecsv")
  dir.create(mon_dossier_temp)
  save_as_csv(df=iris, path = file.path(mon_dossier_temp, "output.csv"))
})
```
  


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_export_results.Rmd", vignette_name = "Exporter les résultats")
```
