# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("save_as_csv works", {
  expect_true(inherits(save_as_csv, "function")) 
  mon_dossier_temp <- tempfile(pattern = "savecsv")
  dir.create(mon_dossier_temp)
  save_as_csv(df=iris, path = file.path(mon_dossier_temp, "output.csv"))
})
