# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title Calcul du nombres de lignes d'un dataframe
#'
#' @param df dataframe
#' @return un message
#' @export 
#' @importFrom glue glue
#' 
#' @examples
#' get_df_nrows(df = iris)
#' get_df_nrows(df = mtcars)
get_df_nrows <- function(df) {
  nrow_df <- nrow(df)
  message(glue("The dataset is composed of {nrow_df} observations"))
  return(nrow_df)
}
