# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand # nolint: line_length_linter.

#' Sauvegarde d'un df en csv
#' 
#' @param df df a exporter
#' @param path chemin de sortie
#' @return le chemin de sortie
#' @importFrom tools file_ext #ne pas oublier
#' @importFrom readr write_csv2 #ne pas oublier
#' @export
#' @examples
#' mon_dossier_temp <- tempfile(pattern ="savecsv")
#' dir.create(mon_dossier_temp)
#' #dans la console : rstudio::filesPanelNaviguate(mon_dossier_temp)
#' save_as_csv(df=iris, path=file.path(mon_dossier_temp, "output.csv"))
#' #Ménage :
#' unlink(mon_dossier_temp, recursive = TRUE)
save_as_csv <- function(df, path){
  
  if (isFALSE(inherits(df,"data.frame"))) {
    stop("Param 'df' must be a dataframe")
  }
  
  if (isFALSE(file_ext(x=path)=="csv")) {
    stop("Param 'path' must have csv extension")
  }
  
  if (isFALSE(dir.exists(dirname(path)))){
    stop("Param 'path' must exist")
  }
    
  write_csv2(df, file = path)
  
  return(path)
    
}
